#!/usr/bin/with-contenv sh

s6-setuidgid www-data

HOST=${HOST:-}
PORT=${PORT:-80}
WORKERS=${WORKERS:-auto}

cd /app

if [ -n "$WATCH" ]; then
  php artisan octane:start --host=$HOST --port=$PORT --workers=1 --watch -n
else
  /scripts/runtime_cache.sh
  php artisan octane:start --host=$HOST --port=$PORT --workers=$WORKERS -n
fi
