#!/usr/bin/with-contenv sh

s6-setuidgid www-data

HOST=${HOST:-}
PORT=${PORT:-80}
WORKERS=${WORKERS:-auto}
RPC_PORT=${RPC_PORT:-6001}

cd /app

if [ "$WATCH" == "true" ]; then
  php artisan octane:start --host=$HOST --port=$PORT --rpc-port=${RPC_PORT} --workers=1 --watch -n
else
  /scripts/runtime_cache.sh
  php artisan octane:start --host=$HOST --port=$PORT --rpc-port=${RPC_PORT} --workers=$WORKERS -n
fi
