#!/usr/bin/with-contenv sh

s6-setuidgid www-data

cd /app

HOST=${HOST:-}
PORT=${PORT:-9090}
WORKERS=${WORKERS:-auto}

if [ "$WATCH" == "true" ]; then
  php artisan grpc:start --host=$HOST --port=$PORT --rpc-port=6002 --workers=1 --watch -n
else
  /scripts/runtime_cache.sh
  php artisan grpc:start --host=$HOST --port=$PORT --rpc-port=6002 --workers=$WORKERS -n
fi
